### ISSUE TITLE
Please add JAVA version to output (csv)

### ISSUE THREAD

**Issue by trust1345** [HynekPetrak/log4shell-finder#11]
Please add JAVA version to output (csv)

**Comment by HynekPetrak** [comment]
not sure how to report it, because there can be per application JVM installed - not in the PATH. And getting version would mean to run the JVM and parse the output. Any wish?

**Comment by trust1345** [comment]
I thought to do this simply based on the version of the library found. That is, for example, according to this table.
https://github.com/HynekPetrak/log4shell-finder/issues/10

**Comment by trust1345** [comment]
Yes, it will probably be problematic to do.
