### ISSUE TITLE
Single binary for windows

### ISSUE THREAD

**Issue by trust1345** [HynekPetrak/log4shell-finder#12]
For all versions of windows, you can make one common binary file. All versions of windows contain 32 subsystems, so such a binary file will work on all Windows systems.

In order to support all versions of windows from windows 7, you need to use version 3.7.9 to build with pyinstaller

**Comment by HynekPetrak** [comment]
Hi @trust1345 , according the Python release page, Python 3.8.x supports Win7 and above. That's actually the Python release I'm using for mswin32 build. Do you have any issues with that?

**Comment by trust1345** [comment]
Hi @HynekPetrak!
You are right, it works without problems (I checked it on test machines). 
So the latest supported build version (to support windows 7) will be 3.8.x
