### ISSUE TITLE
Please build binary file for 32bit system (Linux)

### ISSUE THREAD

**Issue by trust1345** [HynekPetrak/log4shell-finder#13]
Please build binary file for 32bit system (Linux)

**Comment by trust1345** [comment]
Maybe this information will be useful, as example

1. 
http://mirrors.powernet.com.ru/centos-altarch/7.9.2009/isos/i386/CentOS-7-i386-Everything-2009.iso
install it

2. 
`sudo yum -y install yum-utils gcc openssl-devel bzip2-devel libffi-devel python3-dev -y`

3. 
```
cd /tmp/;
curl -O https://www.python.org/ftp/python/3.8.12/Python-3.8.12.tgz;
tar xzf Python-3.8.12.tgz;
cd Python-3.8.12;
sudo ./configure --prefix=/opt/python38 --enable-optimizations --with-system-ffi --with-computed-gotos --enable-loadable-sqlite-extensions --enable-shared LDFLAGS=-Wl,-rpath=/usr/local/lib;
sudo make -j "$(nproc)";
sudo make altinstall;
sudo ldconfig;
sudo rm /tmp/Python-3.8.12.tgz;
```

4. 
```
sudo ln -s /opt/python38/bin/python3.8 /opt/python38/bin/python3;
sudo ln -s /opt/python38/bin/python3.8 /opt/python38/bin/python;
sudo ln -s /opt/python38/bin/python3.8-config /opt/python38/bin/python-config;
sudo ln -s /opt/python38/bin/pydoc3.8 /opt/python38/bin/pydoc;
sudo ln -s /opt/python38/bin/idle3.8 /opt/python38/bin/idle;
sudo ln -s /opt/python38/bin/python3.8 /usr/bin/python38;
sudo ln -s /opt/python38/bin/pip3.8 /opt/python38/bin/pip3;
sudo ln -s /opt/python38/bin/pip3.8 /opt/python38/bin/pip;
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/python38/lib;
```
5.
```
/opt/python38/bin/python -m venv /home/user/venv;
source /home/user/venv/bin/activate
```
6. 
```
pip3 install --upgrade pip;
pip3 install pyinstaller;
```
7.
```
cd /tmp;
mkdir log4shell;
cd log4shell/;
curl -O https://raw.githubusercontent.com/HynekPetrak/log4shell-finder/main/test_log4shell.py
```

8. 
`
pyinstaller -D -F -c test_log4shell.py
`

[test_log4shell_1.2120220120_32bit.zip](https://github.com/HynekPetrak/log4shell-finder/files/7909673/test_log4shell_1.2120220120_32bit.zip)

**Comment by HynekPetrak** [comment]
Other issue is to be compatible with older versions of kernel and glibc. For that I've already prepared a docker container based on Ubuntu:trusty and Python 3.10. 

I'll test first a release based on that one.

What's kernel version in that centos 7 ?

**Comment by trust1345** [comment]
> What's kernel version in that centos 7 ?
3.10.0-1160.53.1.el7.centos.plus.i686

I'll try to buil with https://nuitka.net/doc/user-manual.html
Maybe it will be a less dependent build. In theory, it can also improve performance.

**Comment by trust1345** [comment]
Built with nuitka, for i386 there are also dependencies on glibc. The scanner itself starts much slower with such an assembly than with pyinstaller.
I found a whole list of similar packers
https://pyoxidizer.readthedocs.io/en/latest/pyoxidizer_comparisons.html

I think that with all the negative aspects of pyinstaller (under Linux, 2 versions are needed for binary distribution), in general, there are not so many problems with it

**Comment by trust1345** [comment]
Compiled the current version in issue #21
