### ISSUE TITLE
Please add verdict for Log4J-1.1.1 

### ISSUE THREAD

**Issue by trust1345** [HynekPetrak/log4shell-finder#14]
When the scanner finds Log4J-1.1.1 the verdict turns out to be just an empty space. I think that you need to add a status that would indicate in such cases the need for manual verification, for example manual or add an existing CVE.

`2019-06-19 10:10:10	1.2120220117	333.333.333.333	server.com	Windows	2022	AMD64	Package		...\lib\log4j-core.jar	contains Log4J-1.1.1 <= 1.2.17, JMSAppender.class not found	1.1.1`

**Comment by HynekPetrak** [comment]
fixed
