### ISSUE TITLE
Please add support argument, for line in the csv report when nothing is found on host

### ISSUE THREAD

**Issue by trust1345** [HynekPetrak/log4shell-finder#16]
1 line from the host with the verdict for example CLEAN. It will help for mass rolling scanning of hosts to have also a list of scanned hosts.

"2022-01-25 00:00:00","1.2120220125","192.192.192.192","localhost.localdomain","Linux","6.x86_64","x86_64","Package","CLEAN","","",""

**Comment by HynekPetrak** [comment]
added `--cvs-clean` in ec1b48fda273d5551eff2e651e5d7e6a1b8755a4

**Comment by trust1345** [comment]
Thank you.

**Comment by HynekPetrak** [comment]
I made a typo, it's `--csv-clean` abd just corrected in the last commit.
