### ISSUE TITLE
Please add an argument, that will add to each line of the csv output ( --csv-out ) additional information

### ISSUE THREAD

**Issue by trust1345** [HynekPetrak/log4shell-finder#17]
Please add an argument, that will add to each line of the csv output ( --csv-out ) information about the passed path argument, when the scanner starts, exclude path, and the time spent on scanning the host (even when the verdict is CLEAN), total scanned files and folders.

This information will be useful for analyzing the scanner's work statistics.

Example in attach.
[localhost_10.10.10.10.csv](https://github.com/HynekPetrak/log4shell-finder/files/7938022/localhost_10.10.10.10.csv)

**Comment by HynekPetrak** [comment]
added `--csv-stats` in 75cb4f129110f5da8e8132698ed2b52ad34c405c
