### ISSUE TITLE
Windows: "all" argument to scan all local drives doesn't work on pre-build binary

### ISSUE THREAD

**Issue by wombelix** [HynekPetrak/log4shell-finder#20]
Hi,

I tried the pre-build windows binary from the dist Folder and realized that the `all` option to scan all local drives (https://github.com/HynekPetrak/log4shell-finder/commit/a5cfac0a1fd5678a8c144e59d0e862d274d08965) doesn't work, no drives where found, so nothing was scanned until I had to defined `c:\ d:\` instead.

I tried to build the binary on my own with pyinstaller and was running into the same issue, by checking the code I assumed that there might be a problem with the win32api and win32file import so `drives` will become `none`.

At least for me it was necessary to run `pyinstaller --hidden-import win32api --hidden-import win32file -F ./test_log4shell.py` to enforce that those modules will be included in the binary. Afterwards the `all` option was working as expected, every available drives was found and scanned.

Cheers
Dominik

**Comment by trust1345** [comment]
Try: 

1. use the latest version of the scanner from git 
2. python version 3.8.12
3. pyinstaller build string `test_log4shell.py -y --onefile`

There shouldn't be any problems

**Comment by HynekPetrak** [comment]
Strange I usually test the release on windows. I'll double check on next release and update the readme

**Comment by HynekPetrak** [comment]
Actually it was implemented only in the version 1.22, which has not been released yet back then.

**Comment by HynekPetrak** [comment]
My python 3.8 on Windows did not have pywin32 installed, therefore the  `pyinstaller` build for recent releases was incomplete.
