### ISSUE TITLE
FR add CSV output for massive scan

### ISSUE THREAD

**Issue by trust1345** [HynekPetrak/log4shell-finder#3]
FR
IIt would be great if there was a -c (csv output) option so that you could wrap the scanner in ansible wrapper and use it on a group of machines. Earlier we wrapped the scanner https://github.com/mergebase/log4j-detector but it doesn't keep up with updates a bit and runs slower (there are also problems with memory consumption). As a result, looks like this.
![Снимок экрана от 2021-12-21 17-33-27](https://user-images.githubusercontent.com/64325530/146947047-0ad355f3-de58-45f6-83ae-680cf833fa71.png)
This output is quite convenient for fast processing of a large group of hosts. I have attached an example file. In the attached file, the separator is "@", but you can use for example ","
[role1.4-output.csv](https://github.com/HynekPetrak/log4shell-finder/files/7756114/role1.4-output.csv)

PS. I think it would also be a good idea to make an exception on all Linux hosts /proc by default, this will reduce the speed of scanning (and accessing swap, when touching /proc), but will not worsen its results.

Thanks for the scanner, it's the best.

**Comment by HynekPetrak** [comment]
For avoiding of /proc either use —same-fs or —exclude-dirs /proc

**Comment by HynekPetrak** [comment]
csv added in v1.8

**Comment by trust1345** [comment]
Thank you very much!

Works great, thank you. Ideally, add the scan date and OS version.
