### ISSUE TITLE
Automatic generation of the output file name using the hostname_ip.csv template

### ISSUE THREAD

**Issue by trust1345** [HynekPetrak/log4shell-finder#4]
FR
For mass scanning of a host group by a scanner, it would be great if the name of the output file (when using some key) was generated automatically using the hostname_ip.csv template.
This will allow you to collect all the received files into one directory (without thinking about the coincidence of file names) and executing, for example 
cat ./*.csv > report_all.csv
to get a general report.

Thanks for the scanner.

**Comment by HynekPetrak** [comment]
can't you generate the filename via ansible playbook itself?

**Comment by HynekPetrak** [comment]
done in release v1.8

**Comment by trust1345** [comment]
Works great, thank you.
