### ISSUE TITLE
Doesn't scale well to multiple CPU cores

### ISSUE THREAD

**Issue by jachstet-sea** [HynekPetrak/log4shell-finder#7]
I've been running this on our AMD Threadripper 2990WX machine and since it took more than 5 minutes, I started to investigate why.

It looks like the disk is bored and only one CPU core is loaded with 100%, all other cores are also idling.

I didn't have a look at the source code but maybe a two-pass approach might speed things up:
* Build a list of all files to be scanned. This probably cannot be parallelized much
* Go through the list in several threads so it's not just one CPU core doing all the work

**Comment by HynekPetrak** [comment]
That's actually how it works. For each folder a number of threads is processing files in parallel. Try to show progress with --progress 1 argument. Once it get stuck run lsof (on Linux) to identify the problematic file.
Note I could not workaround zip-bombs. So it's better to skip them with --exclude-dirs argument. Also it's recommended to use --same-fs to avoid scanning mount points and rather list file system roots explicitly

**Comment by jachstet-sea** [comment]
Ah, okay, perfect then :) Thanks for the quick answer
I've checked with `--progress 1` and it's not a single file that blocks it. It's the main thread that's constantly at 100% and worker threads come and go but no more than about 5 at a time or so.
Well, nevermind, system has been scanned, all good :)

**Comment by HynekPetrak** [comment]
@jachstet-sea If cpu is not utilized well enough, the i/o might be the bottleneck. I’m planning to do a bit more experiments and maybe delegate more work to threads, need to be empirically proven

**Comment by HynekPetrak** [comment]
Hi @jachstet-sea  can you test current version from git? I was able to shorten run time by yet another 20% with the latest changes.

**Comment by HynekPetrak** [comment]
Added also —threads N argument for adjusting number of threads from command line
