### ISSUE TITLE
Several improvements to the scanner

### ISSUE THREAD

**Issue by trust1345** [HynekPetrak/log4shell-finder#9]
Thanks for the scanner, it's great.
As part of our use, we have made a few minor improvements to it, maybe they will be useful to everyone.

1. CVSS score change according to nvd.nist.gov
2. UTF8 patch, fixes problems on Windows systems with a non-UTF 8 locale installed in path
3. all new argument, for windows version (close to similar --same-fs on Linux)
remove header to --cvs-out, it is not needed when you do multiple system scans, and then combine the file into one. For example, running on a host group (Windows) from a network drive with the parameter
`log4shell.exe all --csv-out`
and after scanning the collection to 1 report 
`type *.csv > all.csv` (for Windows)
`cat .csv > all.csv`(for Linux)
4. some changes to cvs output, it becomes more convenient
[log4shell_1.22.2.6.zip](https://github.com/HynekPetrak/log4shell-finder/files/7881444/log4shell_1.22.2.6.zip)

**Comment by HynekPetrak** [comment]
Hi @trust1345 ,
please test the latest git version before I release it, whether it's ok for you.
- I didn't use psutil, because I want to keep no dependencies, just using the python standard library
- I added `--no-csv-header` for you to control whether to output csv header or not.
- added the other points from your list.

**Comment by HynekPetrak** [comment]
implemented in https://github.com/HynekPetrak/log4shell-finder/commit/bce24af89de80b74ac45a1c77d7dd98b8a8679d5

**Comment by trust1345** [comment]
Thanks. I'll write as soon as I check.
Of course, I would not like to include psutil, but the ability to specify all local disks on Windows at startup (instead of explicitly specifying them, all) is quite an interesting option, as it seems to me.

**Comment by HynekPetrak** [comment]
@trust1345 what I mean, that I've implemented the feature without psutil . Just test it

**Comment by trust1345** [comment]
@HynekPetrak  I'm already trying.

a small error when copying (extra column "hostname")
```
905    found_items_columns = ["datetime", "ver", "ip", "hostname", "fqdn",
906                           "OS", "Release", "arch",
907                           "container", "status", "path", "message", "pom_version"]
```
it needs to be
```
    found_items_columns = ["datetime", "ver", "ip", "fqdn",
                           "OS", "Release", "arch",
                           "container", "status", "path", "message", "pom_version"]
```
Everything works, thank you.

**Comment by HynekPetrak** [comment]
Well you added hostname, I initially had fqdn. I need to keep fqdn, so I added hostname proposed by you.
If you are fine with fqdn, then I remove the hostname again

**Comment by trust1345** [comment]
FQDN is enough, I suggest deleting the hostname. 

PS. Earlier I used to change what the hostname is.

**Comment by HynekPetrak** [comment]
done.
